### ISSUE TITLE
Inheritable options causes panic

### ISSUE THREAD

**Issue by myOmikron** [hellflame/argparse#17]
```go
func main() {	
        parser := argparse.NewParser("q-scheduler", "", nil)

	startParser := parser.AddCommand("start", "Starts the scheduler", &argparse.ParserConfig{
		DisableHelp: true,
	})

	initParser := parser.AddCommand("init", "", &argparse.ParserConfig{
		DisableHelp: true,
	})

	configPath := parser.String("", "config-path", &argparse.Option{
		Default:     "/etc/q-scheduler/config.toml",
		Help:        "Path to the configuration file of q-scheduler.",
		Inheritable: true,
	})

	if err := parser.Parse(nil); err != nil {
		fmt.Println(err.Error())
		return
	}
}
```
This panics:

```bash
omikron@xps13 ~/g/q-scheduler (main) [1]> go run cmd/q-scheduler/main.go start --config-path abc
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/hellflame/argparse.min({0xe57678?, 0x84210842?, 0xc0001738c0?})
        /opt/go/pkg/mod/github.com/hellflame/argparse@v1.8.0/levenshtein.go:63 +0x7c
github.com/hellflame/argparse.decideMatch({0x7ffcaffd478c, 0xd}, {0x0, 0x0, 0xc0002da460?})
        /opt/go/pkg/mod/github.com/hellflame/argparse@v1.8.0/levenshtein.go:8 +0x87
github.com/hellflame/argparse.(*Parser).Parse(0xc0002da380, {0xc000132020?, 0x7ffcaffd4786?, 0x5?})
        /opt/go/pkg/mod/github.com/hellflame/argparse@v1.8.0/parse.go:502 +0x88d
github.com/hellflame/argparse.(*Parser).Parse(0xc0002da1c0, {0x0?, 0x0?, 0xa4849d?})
        /opt/go/pkg/mod/github.com/hellflame/argparse@v1.8.0/parse.go:432 +0x19b
main.main()
        /home/omikron/git/q-scheduler/cmd/q-scheduler/main.go:28 +0x145
exit status 2
```

**Comment by myOmikron** [comment]
May it be an option to change the behavior from `Inheritable` that it is possible to inherit the option on all parsers not just the ones defined after the option?

**Comment by hellflame** [comment]
> May it be an option to change the behavior from Inheritable that it is possible to inherit the option on all parsers not just the ones defined after the option?

Well, this is what I wanted to do first, but it may be too complex to use it. So I just took the simple way.

The panic can be fixed in no time.

**Comment by myOmikron** [comment]
I get the point, but I don't think, the way its implemented now, reduce the complexity.

I'd say if one is thinking about an option that is used in multiple, but not all parsers, the probability will be high, the user want to use the feature on multiple different parsers. 

In my understanding this won't be possible right now

**Comment by hellflame** [comment]
Well, in some cases like only one argument to inherit or arguments with the same hierarchy to inherit,  you can choose to inherit it or them in all parsers or some parsers. This way, I think it's easy to use the inherit here.

And here, `one option` is easy to control to be inherited by one or many parsers actually. This `one option` should be declared before that or those parsers.
> an option that is used in multiple, but not all parsers

Or I just misunderstand the scenario =.=

**Comment by myOmikron** [comment]
Maybe with this code example, the problem will be clearer. `bcArgs` should be only usable by `bParser` and `cParser`, `cdArgs` only by `cParser` and `dParser`.

```go
package main

import (
	"fmt"
	"github.com/hellflame/argparse"
)

func main() {
	parser := argparse.NewParser("", "", nil)
	aParser := parser.AddCommand("a", "", nil)
	bcArgs := parser.Strings("", "bc", &argparse.Option{Inheritable: true})
	bParser := parser.AddCommand("b", "", nil)
	cdArgs := parser.Strings("", "cd", &argparse.Option{Inheritable: true})
	cParser := parser.AddCommand("c", "", nil)
	dParser := parser.AddCommand("d", "", nil)

	err := parser.Parse(nil)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	fmt.Println(aParser, bcArgs, bParser, cdArgs, cParser, dParser)
}
```

**Comment by myOmikron** [comment]
Another topic would be, that options with `Inheritable` option should (in my opinion) not be registered on the main parser, which is by now the case.

**Comment by hellflame** [comment]
I designed this `Inheritable` feature main to deal the scenario described in #15. In which the sub parsers need to inherit the  `Inheritable` option. I guess if the sub parsers don't inherit from the main parser, it can't be called *inherit*, right? Or some `virtual option` feature should be implemented? ......
I don't know what's your case would be like?  And that's right, this would be another topic to discuss.

**Comment by hellflame** [comment]
Sorry for the problem.  
Panic problem is fixed by version `1.8.1`.
Closing this issue for the panic is fixed, raise another issue for more topic to discuss.
